config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :cards
  resources :imports
  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord

    serialize :rewards, JSON

end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/import.rb
class Import < ApplicationRecord

    belongs_to :user

    def sheet_upload=(incoming_file)
        self.data = incoming_file.read
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, if: Proc.new {|c| c.request.format.json?}
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all.order(:nickname)
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.fetch(:card, {})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, if: Proc.new {|c| c.request.format.json?}

  def index
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, if: Proc.new {|c| c.request.format.json?}
  before_action :set_import, only: [:show, :edit, :update, :destroy]

  # GET /imports
  # GET /imports.json
  def index
    @imports = Import.all
  end

  # GET /imports/1
  # GET /imports/1.json
  def show
  end

  # GET /imports/new
  def new
    @import = Import.new
  end

  # GET /imports/1/edit
  def edit
  end

  # POST /imports
  # POST /imports.json
  def create
    return if params[:sheet].blank?
    @import = Import.new(import_params)
    @import.sheet_upload = params[:sheet]
    @import.user = current_user

    respond_to do |format|
      if @import.save
        format.html { redirect_to @import, notice: 'Import was successfully created.' }
        format.json { render :show, status: :created, location: @import }
      else
        format.html { render :new }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imports/1
  # PATCH/PUT /imports/1.json
  def update
    respond_to do |format|
      if @import.update(import_params)
        format.html { redirect_to @import, notice: 'Import was successfully updated.' }
        format.json { render :show, status: :ok, location: @import }
      else
        format.html { render :edit }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imports/1
  # DELETE /imports/1.json
  def destroy
    @import.destroy
    respond_to do |format|
      format.html { redirect_to imports_url, notice: 'Import was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_import
      @import = Import.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def import_params
      params.fetch(:import, {})
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    respond_to :json
    skip_before_action :verify_authenticity_token
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    respond_to :json
    skip_before_action :verify_authenticity_token
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th width="15%" scope="col">Card</th>
            <th scope="col">Cashback Percentage</th>
          </tr>
        </thead>
        <tbody>
          <% @cards.each do |card| %>
            <tr>
              <td><i class="material-icons">credit_card</i> <%= card.nickname %></td>
              <td>
                <% unless card.rewards.nil? %>
                  <% card.rewards.each do |reward| %>
                    <span class="chip mb-2"><i class="chip-icon"><%= reward["cashback"].to_f * 100 %></i><%= reward["category"] %></span>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      
    </div>
  </div>
</div>

app/views/imports/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <%= form_with(model: import, local: true, multipart: true) do |form| %>
        <% if import.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(import.errors.count, "error") %> prohibited this import from being saved:</h2>

            <ul>
            <% import.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="custom-file">
          <%= file_field_tag 'sheet' %>
          <label class="custom-file-label" for="customFile">Select completed sheet</label>
        </div>

        <div class="actions">
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/imports/edit.html.erb
<h1>Editing Import</h1>

<%= render 'form', import: @import %>

<%= link_to 'Show', @import %> |
<%= link_to 'Back', imports_path %>

app/views/imports/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Download the Excel App</h5>
          <p class="card-text">This allows all your transaction processing to be performed on your computer.</p>
        </div>
        <div class="list-group list-group-flush" id="accordionTwo">
          <div class="expansion-panel list-group-item">
            <a aria-controls="collapseFour" aria-expanded="false" class="expansion-panel-toggler collapsed" data-toggle="collapse" href="#collapseFour" id="headingFour">
              <strong class="text-danger">Before you begin</strong>
              <div class="expansion-panel-icon ml-3 text-black-secondary">
                <i class="collapsed-show material-icons">keyboard_arrow_down</i>
                <i class="collapsed-hide material-icons">keyboard_arrow_up</i>
              </div>
            </a>
            <div aria-labelledby="headingFour" class="collapse" data-parent="#accordionTwo" id="collapseFour">
              <div class="expansion-panel-body">
                <p>You will need the following before loading your transactions:</p>
                <ul>
                  <li>Excel 2007 or higher installed on your local computer</li>
                  <li>A copy of your bank statement in .csv format</li>
                </ul>
                <p class="mb-0">If your bank doesn't offer .csv export, or you don't have the file at hand right now, download our <%= link_to 'sample file', '#' %>.</p>
              </div>
            </div>
          </div>
          <div class="expansion-panel list-group-item">
            <a aria-controls="collapseFive" aria-expanded="false" class="expansion-panel-toggler collapsed" data-toggle="collapse" href="#collapseFive" id="headingFive">
              Download and run the workbook
              <div class="expansion-panel-icon ml-3 text-black-secondary">
                <i class="collapsed-show material-icons">keyboard_arrow_down</i>
                <i class="collapsed-hide material-icons">keyboard_arrow_up</i>
              </div>
            </a>
            <div aria-labelledby="headingFive" class="collapse" data-parent="#accordionTwo" id="collapseFive">
              <div class="expansion-panel-body">
                <%= link_to raw('<i class="material-icons">cloud_download</i> Download Excel App .xlsm'), '#', class: 'btn btn-block btn-lg btn-success mb-4' %>
                <p>After downloading and opening the workbook, you may have to leave "protected view":</p>
                <%= image_tag 'protectedview.png', class: 'mb-3' %>
                <p>You might also have to "enable content":</p>
                <%= image_tag 'enablecontent.png', class: 'mb-3' %>
              </div>
            </div>
          </div>
          <div class="expansion-panel list-group-item">
            <a aria-controls="collapseSix" aria-expanded="false" class="expansion-panel-toggler collapsed" data-toggle="collapse" href="#collapseSix" id="headingFive">
              Upload your results for advanced analytics
              <div class="expansion-panel-icon ml-3 text-black-secondary">
                <i class="collapsed-show material-icons">keyboard_arrow_down</i>
                <i class="collapsed-hide material-icons">keyboard_arrow_up</i>
              </div>
            </a>
            <div aria-labelledby="headingSix" class="collapse" data-parent="#accordionTwo" id="collapseSix">
              <div class="expansion-panel-body">
                <p>After using the Excel App, you can upload it here for some good looking graphs and statistics.</p>
                <%= link_to 'New Upload', new_import_url, class: 'btn btn-lg btn-primary' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row my-5">
    <div class="col text-center">
      <h4 class="mb-0">OR</h4>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title text-muted">Connect your Bank Account (coming soon)</h5>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/imports/new.html.erb
<div class="container">
  <div class="row align-items-center justify-content-around">
    <div class="col-6">
      <%= form_with(model: @import, local: true, multipart: true) do |form| %>
        <% if @import.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@import.errors.count, "error") %> prohibited this import from being saved:</h2>

            <ul>
            <% @import.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group mb-4">
          <div class="custom-file">
            <%= file_field_tag 'sheet', class: 'custom-file-input' %>
            <label class="custom-file-label" for="customFile">Click to select completed sheet...</label>
          </div>
        </div>

        <div class="actions">
          <%= form.submit 'Upload', class: 'btn btn-block btn-lg btn-primary mb-3' %>
          <%= link_to 'Back', imports_url, class: 'btn btn-block btn-sm btn-light' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/imports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_import_path(@import) %> |
<%= link_to 'Back', imports_path %>

app/views/includes/_navbar.html.erb
<nav class="navbar navbar-dark bg-primary mb-5">
  <div class="container">
    <%= link_to 'StreetCredit', root_url, class: 'navbar-brand' %>
    <ul class="navbar-nav mr-auto">
      <!-- <li class="nav-item">
        <%= link_to 'Cards', cards_url, class: 'nav-link' %>
      </li> -->
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.email %></a>
          <div class="dropdown-menu">
            <%= link_to 'Sign Out', destroy_user_session_url, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_url, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'includes/navbar' %>
    <% unless notice.nil? && alert.nil? %>
      <div class="container">
        <% if notice.present? %>
          <div class="alert alert-light mb-2" role="alert">
            <%= notice %>
          </div>
        <% end %>
        <% if alert.present? %>
          <div class="alert alert-danger" role="alert">
            <%= alert %>
          </div>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>